#ifndef VERSION_H
#define VERSION_H

// These variables are autogenerated and compiled
// into the library by the version.cmake script
extern "C"
{
    extern const char *GIT_TAG;
    extern const char *GIT_REV;
    extern const char *GIT_BRANCH;
}

#endif